import type { Branch, Product } from "./types";
import { initialBranches } from "./preview";

// Catálogo de demostración y sucursales demo, solo desarrollo y solo con
// CATALOG_DEMO=true. Los precios, marcas, tiendas, direcciones, horarios y
// teléfonos son de ejemplo (los locales marcados como DEMO son ficticios):
// sirven para probar el flujo completo (catálogo → filtros → carrito →
// cotización → WhatsApp) y el mapa interactivo sin base de datos real.
// No representan inventario ni negocios reales de Rancing Mau.

export function demoEnabled() {
  return (
    process.env.NODE_ENV !== "production" &&
    process.env.CATALOG_DEMO === "true"
  );
}

const DEMO_NOTICE =
  "PRODUCTO DE DEMOSTRACIÓN con precio de ejemplo para probar el catálogo, los filtros, el mapa y el envío por WhatsApp. No es el precio oficial, no confirma disponibilidad ni compatibilidad; la información real la publica Rancing Mau en el panel administrativo.";

const branchDescriptor = (
  branch: Branch,
  extra: Omit<Branch, "id" | "name" | "slug" | "city"> &
    Partial<Pick<Branch, "city">>,
): Branch => ({ ...branch, ...extra, demo: true });

export const demoBranches: Branch[] = [
  branchDescriptor(initialBranches[0], {
    address: "Centro, 2ª avenida, frente al parque (dirección DEMO)",
    schedule: "Lunes a sábado, 8:00 a 18:00",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.3186,-87.6834",
    lat: 14.3186,
    lng: -87.6834,
    description:
      "Tienda principal de demostración en La Paz: repuestos, lubricantes y accesorios para tu moto.",
  }),
  branchDescriptor(initialBranches[1], {
    address: "Barrio El Calvario, 4ª calle (dirección DEMO)",
    schedule: "Lunes a sábado, 8:30 a 17:30",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.3221,-87.6777",
    lat: 14.3221,
    lng: -87.6777,
    description:
      "Segunda tienda de demostración en La Paz, especializada en mecánica y transmisión.",
  }),
  branchDescriptor(initialBranches[2], {
    address: "Calle principal, contiguo al mercado (dirección DEMO)",
    schedule: "Lunes a sábado, 8:00 a 17:00",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.1572,-88.0356",
    lat: 14.1572,
    lng: -88.0356,
    description:
      "Tienda de demostración en Marcala para repuestos y accesorios de la zona.",
  }),
  {
    id: "00000000-0000-4000-8000-000000000004",
    name: "SIGUATEPEQUE TIENDA 4",
    slug: "siguatepeque-tienda-4",
    city: "Siguatepeque",
    address: "Salida a Marcala, frente a la gasolinera (dirección DEMO)",
    schedule: "Lunes a sábado, 9:00 a 18:00",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.598,-87.833",
    lat: 14.598,
    lng: -87.833,
    demo: true,
    description:
      "Punto de demostración en Siguatepeque para atender la ruta entre Comayagua y la sierra.",
  },
  {
    id: "00000000-0000-4000-8000-000000000005",
    name: "LA ESPERANZA TIENDA 5",
    slug: "la-esperanza-tienda-5",
    city: "La Esperanza",
    address: "Avenida Morazán, sector del parque (dirección DEMO)",
    schedule: "Lunes a sábado, 8:30 a 17:30",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.3144,-88.1788",
    lat: 14.3144,
    lng: -88.1788,
    demo: true,
    description:
      "Tienda de demostración en La Esperanza, Intibucá, para la zona occidente.",
  },
  {
    id: "00000000-0000-4000-8000-000000000006",
    name: "JESÚS DE OTORO TIENDA 6",
    slug: "jesus-de-otoro-tienda-6",
    city: "Jesús de Otoro",
    address: "Barrio abajo, salida a La Misión (dirección DEMO)",
    schedule: "Lunes a sábado, 8:00 a 18:00",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.4847,-88.0017",
    lat: 14.4847,
    lng: -88.0017,
    demo: true,
    description:
      "Sucursal de demostración en Jesús de Otoro con repuestos de uso diario.",
  },
  {
    id: "00000000-0000-4000-8000-000000000007",
    name: "SAN PEDRO DE TUTULE TIENDA 7",
    slug: "san-pedro-de-tutule-tienda-7",
    city: "San Pedro de Tutule",
    address: "Centro, contiguo a la alcaldía (dirección DEMO)",
    schedule: "Lunes a sábado, 8:00 a 16:30",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.2489,-87.8533",
    lat: 14.2489,
    lng: -87.8533,
    demo: true,
    description:
      "Más cerca de tu ruta por el departamento de La Paz (marcador de demostración).",
  },
  {
    id: "00000000-0000-4000-8000-000000000008",
    name: "COMAYAGUA TIENDA 8",
    slug: "comayagua-tienda-8",
    city: "Comayagua",
    address: "Barrio La Alameda, avenida de los comercios (dirección DEMO)",
    schedule: "Lunes a domingo, 9:00 a 19:00",
    whatsapp_number: null,
    google_maps_url: "https://www.google.com/maps/search/?api=1&query=14.4511,-87.637",
    lat: 14.4511,
    lng: -87.637,
    demo: true,
    description:
      "Punto de demostración en Comayagua, en plena ruta de las dos grandes ciudades.",
  },
];

type DemoRow = {
  slug: string;
  name: string;
  brand: string;
  category: string;
  image: string;
  base_price: number;
  promo_price?: number;
  status?: "available" | "out_of_stock" | "promotion" | "pending";
  featured?: boolean;
  available: number[];
  compatibility?: string;
};

const PLACEHOLDER = (category: string) => {
  const map: Record<string, string> = {
    "Aceites y lubricantes": "demo-lubricantes.png",
    Motor: "demo-motor.png",
    Transmisión: "demo-transmision.png",
    Frenos: "demo-frenos.png",
    "Suspensión": "demo-suspension.png",
    Electricidad: "demo-electricidad.png",
    Accesorios: "demo-accesorios.png",
    Cascos: "demo-cascos.png",
    "Llantas y neumáticos": "demo-llantas.png",
    "Repuestos universales": "demo-universales.png",
  };
  return `/images/productos/${map[category] ?? "demo-universales.png"}`;
};

const POR_CONFIRMAR = "Compatibilidad por confirmar";

// 100 productos de demostración repartidos en 10 categorías.
// Los 5 primeros reproducen el catálogo original para no romper el flujo
// documentado en tests/demo (total L 564 y promoción con 2 unidades).
const rows: DemoRow[] = [
  {
    slug: "aceite-motul-7100",
    name: "Aceite Motul 7100 4T 10W-40 (DEMO)",
    brand: "Motul",
    category: "Aceites y lubricantes",
    image: "aceitemotul7100.jpeg",
    base_price: 320,
    promo_price: 289,
    featured: true,
    available: [1, 2, 3],
  },
  {
    slug: "aceite-castrol-actevo",
    name: "Aceite Castrol Actevo 4T 20W-50 (DEMO)",
    brand: "Castrol",
    category: "Aceites y lubricantes",
    image: "aceiteactevo.jpeg",
    base_price: 275,
    featured: true,
    available: [1, 2, 3],
  },
  {
    slug: "aceite-bajaj-sintetico",
    name: "Aceite Bajaj 4T sintético (DEMO)",
    brand: "Bajaj",
    category: "Aceites y lubricantes",
    image: "aceitebajaj1.2fullsintetico.jpeg",
    base_price: 165,
    featured: true,
    available: [1, 2],
  },
  {
    slug: "aceite-yamalube",
    name: "Aceite Yamalube 4T (DEMO)",
    brand: "Yamalube",
    category: "Aceites y lubricantes",
    image: "yamalubeaceite.jpeg",
    base_price: 230,
    featured: true,
    available: [1, 2, 3],
  },
  {
    slug: "aceite-bajaj-4t",
    name: "Aceite Bajaj 4T (DEMO)",
    brand: "Bajaj",
    category: "Aceites y lubricantes",
    image: "aceite1.2bajaj.webp",
    base_price: 150,
    promo_price: 135,
    available: [1],
  },

  // Aceites y lubricantes (9 adicionales → 14 en total)
  {
    slug: "aceite-motul-5100",
    name: "Aceite Motul 5100 4T 10W-40 (DEMO)",
    brand: "Motul",
    category: "Aceites y lubricantes",
    image: "aceitemotul5100.jpeg",
    base_price: 285,
    available: [1, 2, 3, 5],
    compatibility: "Motos 4T de 100 a 250 cc",
  },
  {
    slug: "aceite-motul-3000",
    name: "Aceite Motul 3000 4T 20W-50 (DEMO)",
    brand: "Motul",
    category: "Aceites y lubricantes",
    image: "aceitemotul300.jpeg",
    base_price: 250,
    promo_price: 235,
    available: [1, 2, 3, 4, 6],
  },
  {
    slug: "aceite-motul-2t",
    name: "Aceite Motul 2T semisintético (DEMO)",
    brand: "Motul",
    category: "Aceites y lubricantes",
    image: "aceitemotul7100.jpeg",
    base_price: 180,
    available: [1, 3, 7],
    compatibility: "Motos 2T (mezcla motor 50:1)",
  },
  {
    slug: "aceite-castrol-power1",
    name: "Aceite Castrol Power1 4T 10W-30 (DEMO)",
    brand: "Castrol",
    category: "Aceites y lubricantes",
    image: "aceitepower.webp",
    base_price: 260,
    available: [2, 3, 5],
  },
  {
    slug: "aceite-valvoline-4t",
    name: "Aceite Valvoline 4T 20W-50 (DEMO)",
    brand: "Valvoline",
    category: "Aceites y lubricantes",
    image: "aceiteactevo.jpeg",
    base_price: 190,
    status: "out_of_stock",
    available: [1, 2, 4, 8],
  },
  {
    slug: "aceite-mobil-4t",
    name: "Aceite Mobil Super Moto 4T 20W-50 (DEMO)",
    brand: "Mobil",
    category: "Aceites y lubricantes",
    image: "yamalubeaceite.jpeg",
    base_price: 175,
    available: [1, 2, 3, 6],
  },
  {
    slug: "aceite-shell-advance",
    name: "Aceite Shell Advance 4T 20W-50 (DEMO)",
    brand: "Shell",
    category: "Aceites y lubricantes",
    image: "aceitebajaj1.2fullsintetico.jpeg",
    base_price: 210,
    available: [1, 3, 5, 7],
  },
  {
    slug: "aceite-elf-4t",
    name: "Aceite Elf Moto 4T 20W-50 (DEMO)",
    brand: "Elf",
    category: "Aceites y lubricantes",
    image: "aceitemotul300.jpeg",
    base_price: 205,
    status: "out_of_stock",
    available: [2, 4, 6],
  },
  {
    slug: "aceite-repsol-4t",
    name: "Aceite Repsol Moto 4T 20W-50 (DEMO)",
    brand: "Repsol",
    category: "Aceites y lubricantes",
    image: "demo-lubricantes.png",
    base_price: 215,
    promo_price: 199,
    available: [1, 2, 3, 8],
    compatibility: "Motos 4T de 100 a 150 cc",
  },

  // Motor
  {
    slug: "piston-cg125",
    name: "Kit pistón CG125 56.5 mm c/aros (DEMO)",
    brand: "CG",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 450,
    available: [1, 2, 3],
    compatibility: "Compatibilidad por confirmar (referencia CG125)",
  },
  {
    slug: "piston-cg150",
    name: "Kit pistón CG150 62 mm c/aros (DEMO)",
    brand: "CG",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 520,
    available: [1, 3, 5],
  },
  {
    slug: "anillos-piston",
    name: "Juego de aros de pistón 52.4 mm (DEMO)",
    brand: "CG",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 120,
    available: [1, 2, 4, 7],
  },
  {
    slug: "juego-valvulas",
    name: "Juego de válvulas admisión/escape (DEMO)",
    brand: "UFIT",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 95,
    status: "out_of_stock",
    available: [2, 3, 6],
  },
  {
    slug: "empaque-motor",
    name: "Empaque completo motor 125cc (DEMO)",
    brand: "UFIT",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 140,
    available: [1, 2, 3, 8],
  },
  {
    slug: "cadena-diastribucion",
    name: "Cadena de distribución para motor (DEMO)",
    brand: "Tsubaki",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 210,
    available: [1, 3, 5],
  },
  {
    slug: "tensor-cadena",
    name: "Tensor de cadena de distribución (DEMO)",
    brand: "UFIT",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 180,
    available: [2, 4, 6],
  },
  {
    slug: "carburador-pz26",
    name: "Carburador tipo PZ26 CSV (DEMO)",
    brand: "PZ",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 280,
    available: [1, 2, 3, 7],
  },
  {
    slug: "kit-reparacion-carburador",
    name: "Kit de reparación de carburador (DEMO)",
    brand: "PZ",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 45,
    available: [1, 3, 4, 8],
  },
  {
    slug: "balancines",
    name: "Juego de balancines de válvula (DEMO)",
    brand: "UFIT",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 130,
    status: "out_of_stock",
    available: [2, 5],
  },
  {
    slug: "arbol-levas",
    name: "Árbol de levas para 125cc (DEMO)",
    brand: "CG",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 340,
    available: [1, 3, 6],
  },
  {
    slug: "cilindro-cg125",
    name: "Cilindro CG125 perforado a 56.5 mm (DEMO)",
    brand: "CG",
    category: "Motor",
    image: "demo-motor.png",
    base_price: 480,
    available: [2, 3, 7],
  },

  // Transmisión
  {
    slug: "cadena-428-132",
    name: "Cadena 428 x 132 eslabones (DEMO)",
    brand: "DID",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 320,
    available: [1, 2, 3],
    compatibility: "Motos 100-150 cc con transmisión 428",
  },
  {
    slug: "cadena-428-120",
    name: "Cadena 428 x 120 eslabones (DEMO)",
    brand: "RK",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 290,
    available: [1, 3, 4],
  },
  {
    slug: "cadena-420-118",
    name: "Cadena 420 x 118 eslabones (DEMO)",
    brand: "DID",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 240,
    status: "out_of_stock",
    available: [2, 5, 7],
  },
  {
    slug: "piñon-delantero-15",
    name: "Piñón delantero 15T (DEMO)",
    brand: "RK",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 85,
    available: [1, 2, 3, 6],
  },
  {
    slug: "piñon-trasero-42",
    name: "Corona trasera 42T (DEMO)",
    brand: "RK",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 140,
    available: [1, 3, 5],
  },
  {
    slug: "kit-arrastre",
    name: "Kit de arrastre cadena + piñones (DEMO)",
    brand: "DID",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 520,
    promo_price: 479,
    available: [1, 2, 3, 8],
  },
  {
    slug: "disco-embrague",
    name: "Disco de embrague (juego) (DEMO)",
    brand: "UFIT",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 260,
    available: [1, 2, 4],
  },
  {
    slug: "plato-presion-embrague",
    name: "Plato de presión de embrague (DEMO)",
    brand: "UFIT",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 220,
    status: "out_of_stock",
    available: [3, 6],
  },
  {
    slug: "resortes-embrague",
    name: "Juego de resortes de embrague (DEMO)",
    brand: "UFIT",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 60,
    available: [1, 3, 5, 7],
  },
  {
    slug: "guardacadena",
    name: "Guardacadena superior plástico (DEMO)",
    brand: "Racing Mau",
    category: "Transmisión",
    image: "demo-transmision.png",
    base_price: 90,
    available: [2, 4, 8],
  },

  // Frenos
  {
    slug: "balatas-delanteras",
    name: "Pastilla de freno delantera (juego) (DEMO)",
    brand: "DISCO",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 110,
    available: [1, 2, 3],
  },
  {
    slug: "balatas-traseras",
    name: "Pastilla de freno trasera (juego) (DEMO)",
    brand: "DISCO",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 95,
    available: [1, 3, 5],
  },
  {
    slug: "zapata-freno-cb",
    name: "Zapata de freno 125cc (DEMO)",
    brand: "CG",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 70,
    promo_price: 59,
    available: [1, 2, 4, 6],
  },
  {
    slug: "disco-freno-trasero",
    name: "Disco de freno trasero (DEMO)",
    brand: "CG",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 350,
    available: [1, 3, 7],
  },
  {
    slug: "bomba-freno",
    name: "Bomba de freno principal (DEMO)",
    brand: "CG",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 300,
    status: "out_of_stock",
    available: [2, 5],
  },
  {
    slug: "liquido-frenos-dot4",
    name: "Líquido de frenos DOT 4 250ml (DEMO)",
    brand: "Racing Mau",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 65,
    available: [1, 2, 3, 8],
  },
  {
    slug: "manguera-freno",
    name: "Manguera de freno reforzada (DEMO)",
    brand: "CG",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 150,
    available: [1, 3, 4],
  },
  {
    slug: "palanca-freno",
    name: "Palanca de freno izquierda (DEMO)",
    brand: "Racing Mau",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 80,
    available: [2, 3, 6, 7],
  },
  {
    slug: "pedal-freno",
    name: "Pedal de freno trasero (DEMO)",
    brand: "CG",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 120,
    available: [1, 5],
  },
  {
    slug: "caliper-freno",
    name: "Caliper de freno delantero (DEMO)",
    brand: "CG",
    category: "Frenos",
    image: "demo-frenos.png",
    base_price: 390,
    available: [2, 3, 8],
  },

  // Suspensión
  {
    slug: "amortiguador-trasero",
    name: "Amortiguador trasero (par) (DEMO)",
    brand: "Showa",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 480,
    available: [1, 2, 3],
  },
  {
    slug: "retenes-horquilla",
    name: "Juego de retenes de horquilla (DEMO)",
    brand: "SKF",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 90,
    available: [1, 3, 5],
  },
  {
    slug: "aceite-horquilla",
    name: "Aceite de horquilla 500ml (DEMO)",
    brand: "Racing Mau",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 85,
    available: [1, 2, 4, 6],
  },
  {
    slug: "jebe-horquilla",
    name: "Guardapolvo de horquilla (par) (DEMO)",
    brand: "SKF",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 45,
    available: [1, 3, 7],
  },
  {
    slug: "tija-superior",
    name: "Tija superior de dirección (DEMO)",
    brand: "CG",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 260,
    status: "out_of_stock",
    available: [2, 5],
  },
  {
    slug: "horquilla-delantera",
    name: "Horquilla delantera completa (DEMO)",
    brand: "CG",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 850,
    available: [1, 3, 8],
  },
  {
    slug: "kit-resortes-horquilla",
    name: "Kit de resortes de horquilla (DEMO)",
    brand: "Showa",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 320,
    available: [2, 3, 6],
  },
  {
    slug: "reten-aro-direccion",
    name: "Juego de balineras de dirección (DEMO)",
    brand: "SKF",
    category: "Suspensión",
    image: "demo-suspension.png",
    base_price: 115,
    available: [1, 3, 4, 7],
  },

  // Electricidad
  {
    slug: "bujia-c7hsa",
    name: "Bujía NGK C7HSA (DEMO)",
    brand: "NGK",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 45,
    available: [1, 2, 3],
    compatibility: "Motos 4T 125-150 cc (referencia estándar)",
  },
  {
    slug: "bujia-c6hsa",
    name: "Bujía NGK C6HSA (DEMO)",
    brand: "NGK",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 45,
    available: [1, 3, 5],
  },
  {
    slug: "bujia-cr7hgp",
    name: "Bujía NGK CR7HGP (DEMO)",
    brand: "NGK",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 65,
    status: "out_of_stock",
    available: [2, 4, 6],
  },
  {
    slug: "cdi-encendido",
    name: "Unidad CDI de encendido (DEMO)",
    brand: "CG",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 250,
    available: [1, 2, 3],
  },
  {
    slug: "bobina-encendido",
    name: "Bobina de encendido CDI (DEMO)",
    brand: "CG",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 180,
    available: [1, 3, 7],
  },
  {
    slug: "rectificador-voltaje",
    name: "Rectificador de voltaje (DEMO)",
    brand: "CG",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 130,
    available: [2, 3, 5],
  },
  {
    slug: "relevador-arranque",
    name: "Relevador de arranque (DEMO)",
    brand: "UFIT",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 75,
    available: [1, 2, 4],
  },
  {
    slug: "bateria-gel-12v",
    name: "Batería gel 12V 5Ah (DEMO)",
    brand: "Yuasa",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 520,
    promo_price: 489,
    available: [1, 2, 3, 8],
  },
  {
    slug: "faro-halogeno",
    name: "Foco halógeno delantero (DEMO)",
    brand: "Philips",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 95,
    available: [1, 3, 6],
  },
  {
    slug: "claxon-12v",
    name: "Claxon 12V (DEMO)",
    brand: "Racing Mau",
    category: "Electricidad",
    image: "demo-electricidad.png",
    base_price: 55,
    available: [2, 3, 4, 7],
  },

  // Accesorios
  {
    slug: "espejo-izquierdo",
    name: "Espejo retrovisor izquierdo (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 85,
    available: [1, 2, 3],
  },
  {
    slug: "espejo-derecho",
    name: "Espejo retrovisor derecho (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 85,
    available: [1, 3, 5],
  },
  {
    slug: "manillas-manillar",
    name: "Manillas antideslizantes para manillar (DEMO)",
    brand: "ProTaper",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 60,
    available: [1, 2, 4],
  },
  {
    slug: "funda-moto",
    name: "Funda protectora para moto (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 240,
    promo_price: 210,
    available: [1, 3, 6],
  },
  {
    slug: "candado-cadenazo",
    name: "Cadenazo de seguridad con candado (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 350,
    available: [1, 2, 3, 7],
  },
  {
    slug: "guaya-acelerador",
    name: "Guaya de acelerador (DEMO)",
    brand: "UFIT",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 45,
    status: "out_of_stock",
    available: [2, 4, 8],
  },
  {
    slug: "guaya-embrague",
    name: "Guaya de embrague (DEMO)",
    brand: "UFIT",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 45,
    available: [1, 3, 5],
  },
  {
    slug: "porta-celular",
    name: "Soporte para celular en manillar (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 130,
    available: [2, 3, 6],
  },
  {
    slug: "kit-tornilleria",
    name: "Kit de tornillería universal para moto (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 150,
    available: [1, 2, 3, 7],
  },
  {
    slug: "rack-trasero",
    name: "Parrilla trasera universal (DEMO)",
    brand: "Racing Mau",
    category: "Accesorios",
    image: "demo-accesorios.png",
    base_price: 320,
    available: [1, 3, 8],
  },

  // Cascos
  {
    slug: "casco-abierto",
    name: "Casco abierto talla M (DEMO)",
    brand: "LS2",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 650,
    available: [1, 2, 3],
  },
  {
    slug: "casco-integral",
    name: "Casco integral talla L (DEMO)",
    brand: "HJC",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 890,
    promo_price: 799,
    available: [1, 3, 5],
  },
  {
    slug: "casco-abatible",
    name: "Casco abatible talla única (DEMO)",
    brand: "LS2",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 980,
    available: [1, 2, 4],
  },
  {
    slug: "casco-infantil",
    name: "Casco integral infantil (DEMO)",
    brand: "Bell",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 480,
    available: [1, 3, 6],
  },
  {
    slug: "visor-casco",
    name: "Visor transparente para casco (DEMO)",
    brand: "LS2",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 120,
    status: "out_of_stock",
    available: [2, 5],
  },
  {
    slug: "guantes-moto",
    name: "Guantes para moto malla (DEMO)",
    brand: "Racing Mau",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 180,
    available: [1, 3, 7],
  },
  {
    slug: "casco-talla-s",
    name: "Casco abierto talla S (DEMO)",
    brand: "Bell",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 620,
    available: [2, 3, 8],
  },
  {
    slug: "casco-talla-xl",
    name: "Casco integral talla XL (DEMO)",
    brand: "HJC",
    category: "Cascos",
    image: "demo-cascos.png",
    base_price: 920,
    available: [1, 2, 3, 5],
  },

  // Llantas y neumáticos
  {
    slug: "llanta-250-17",
    name: "Llanta delantera 2.50-17 (DEMO)",
    brand: "Kenda",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 780,
    available: [1, 2, 3],
  },
  {
    slug: "llanta-275-17",
    name: "Llanta trasera 2.75-17 (DEMO)",
    brand: "Kenda",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 820,
    available: [1, 3, 5],
  },
  {
    slug: "llanta-300-16",
    name: "Llanta universal 3.00-16 (DEMO)",
    brand: "Metzeler",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 860,
    promo_price: 799,
    available: [1, 2, 4],
  },
  {
    slug: "camara-275-17",
    name: "Cámara de llanta 2.75/3.00-17 (DEMO)",
    brand: "Kenda",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 95,
    available: [1, 3, 6],
  },
  {
    slug: "camara-400-18",
    name: "Cámara de llanta 4.00-18 (DEMO)",
    brand: "Kenda",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 130,
    status: "out_of_stock",
    available: [2, 5, 7],
  },
  {
    slug: "llanta-110-90-16",
    name: "Llanta 110/90-16 rib (DEMO)",
    brand: "Metzeler",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 1050,
    available: [1, 2, 3, 8],
  },
  {
    slug: "protector-llanta",
    name: "Protector de cámara (flap) (DEMO)",
    brand: "Racing Mau",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 45,
    available: [1, 3, 4],
  },
  {
    slug: "llanta-400-18",
    name: "Llanta trasera 4.00-18 (DEMO)",
    brand: "Kenda",
    category: "Llantas y neumáticos",
    image: "demo-llantas.png",
    base_price: 980,
    available: [2, 3, 6],
  },

  // Repuestos universales
  {
    slug: "reten-20x35x7",
    name: "Retén 20x35x7 (DEMO)",
    brand: "SKF",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 25,
    available: [1, 2, 3],
    compatibility: POR_CONFIRMAR,
  },
  {
    slug: "reten-22x33x7",
    name: "Retén 22x33x7 (DEMO)",
    brand: "SKF",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 28,
    available: [1, 3, 5],
  },
  {
    slug: "kit-balineras-rueda",
    name: "Kit de balineras para rueda (DEMO)",
    brand: "SKF",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 135,
    available: [1, 2, 4],
  },
  {
    slug: "empacke-tapa",
    name: "Empaque de tapa de culata (DEMO)",
    brand: "UFIT",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 40,
    available: [1, 3, 6],
  },
  {
    slug: "kit-fijaciones",
    name: "Kit de fijaciones y gomitas (DEMO)",
    brand: "Racing Mau",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 35,
    available: [2, 3, 7],
  },
  {
    slug: "lubricante-multiusos",
    name: "Lubricante multiusos en aerosol (DEMO)",
    brand: "Racing Mau",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 90,
    available: [1, 2, 3, 8],
  },
  {
    slug: "junta-homocinetica",
    name: "Junta y guardapolvo universal (DEMO)",
    brand: "UFIT",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 55,
    status: "out_of_stock",
    available: [1, 4, 5],
  },
  {
    slug: "tornilleria-especial",
    name: "Set de tornillería especial para motor (DEMO)",
    brand: "Racing Mau",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 110,
    available: [2, 3, 6],
  },
  {
    slug: "abrazaderas-juego",
    name: "Juego de abrazaderas de manguera (DEMO)",
    brand: "Racing Mau",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 30,
    available: [1, 3, 5, 7],
  },
  {
    slug: "empache-completo-cg",
    name: "Empaque completo de culata CG (DEMO)",
    brand: "UFIT",
    category: "Repuestos universales",
    image: "demo-universales.png",
    base_price: 65,
    available: [1, 2, 3],
  },
];

const descriptionFor = (row: DemoRow) => {
  const head: Record<string, string> = {
    "Aceites y lubricantes":
      "Aceite para motor de moto, presentación demo con precio de ejemplo.",
    Motor:
      "Pieza de motor para motocicleta, referencia de demostración sujeta a confirmación.",
    "Transmisión":
      "Componente de transmisión para moto, referencia de demostración sujeta a confirmación.",
    Frenos:
      "Componente del sistema de frenos para moto, referencia de demostración sujeta a confirmación.",
    "Suspensión":
      "Componente de suspensión para moto, referencia de demostración sujeta a confirmación.",
    Electricidad:
      "Componente eléctrico para motocicleta, referencia de demostración sujeta a confirmación.",
    Accesorios:
      "Accesorio para motocicleta, referencia de demostración sujeta a confirmación.",
    Cascos:
      "Casco o equipo de protección para motociclista, referencia de demostración sujeta a confirmación.",
    "Llantas y neumáticos":
      "Llanta o neumático para motocicleta, referencia de demostración sujeta a confirmación.",
    "Repuestos universales":
      "Repuesto universal para mantenimiento de moto, referencia de demostración sujeta a confirmación.",
  };
  return `${head[row.category] ?? "Repuesto de demostración."} ${DEMO_NOTICE}`;
};

export const demoProducts: Product[] = rows.map((row, index) => ({
  id: `demo-${row.slug}`,
  slug: row.slug,
  name: row.name,
  brand: row.brand,
  sku: `DEMO-${String(index + 1).padStart(3, "0")}`,
  category: row.category,
  description: descriptionFor(row),
  compatibility: row.compatibility ?? null,
  image: row.image.startsWith("demo-")
    ? PLACEHOLDER(row.category)
    : `/api/preview-image/${row.image}`,
  base_price: row.base_price,
  promo_price: row.promo_price ?? null,
  general_status:
    row.status ?? (row.promo_price != null ? "promotion" : "available"),
  featured: Boolean(row.featured),
  branches: demoBranches.map((branch, branchIndex) => ({
    branch_id: branch.id,
    available: row.available.includes(branchIndex + 1),
    branch_price: null,
    branch_promo_price: null,
  })),
}));